### ISSUE TITLE
Update Flask

### ISSUE THREAD

**Issue by vollstock** [Tooloop/Tooloop-Control#11]
Flask has deprecated the use of JSONEncoder (see https://github.com/pallets/flask/pull/4692) which is used to encode APT packages in JSON format.

#10 by @oleprinds fixed this by implicitly installing Flask version 2.2.5

We should, however implement a _real_ fix so we don't end up stuck on old Flask version.

**Comment by vollstock** [comment]
Needs some testing and brought up #13

**Comment by oleprinds** [comment]
It works for me with Flask 2.3.2

**Comment by vollstock** [comment]
fixed in dev branch
